-- Generated by tools/Update-Data.ps1 - do not edit by hand.
-- Source: wago.tools DB2 exports (SkillLineAbility, SpellEffect, CraftingData, SpellReagents, ItemSparse)
-- Build: 12.1.0.69273
-- Generated: 2026-08-15

local _, ns = ...

ns.DATA_BUILD = "12.1.0.69273"

-- Recipes, keyed by the item the recipe produces.
-- `name` is the enUS name, used only as a fallback until the client has the item cached.
ns.lures = {
	[238652] = {
		spellID = 1225943,
		name = "Majestic Eversong Lure",
		reagents = {
			{ id = 238371, count = 8, name = "Arcane Wyrmfish" },
			{ id = 238366, count = 8, name = "Lynxfish" },
		},
	},
	[238653] = {
		spellID = 1225944,
		name = "Majestic Zul'Aman Lure",
		reagents = {
			{ id = 238382, count = 8, name = "Gore Guppy" },
		},
	},
	[238654] = {
		spellID = 1225945,
		name = "Majestic Harandar Lure",
		reagents = {
			{ id = 238375, count = 8, name = "Fungalskin Pike" },
			{ id = 238374, count = 8, name = "Tender Lumifin" },
		},
	},
	[238655] = {
		spellID = 1225946,
		name = "Majestic Voidstorm Lure",
		reagents = {
			{ id = 238373, count = 4, name = "Ominous Octopus" },
		},
	},
	[238656] = {
		spellID = 1225948,
		name = "Grand Beast Lure",
		reagents = {
			{ id = 238380, count = 4, name = "Null Voidfish" },
		},
	},
}

-- Reverse index: which lures consume a given reagent.
ns.reagentToLures = {
	[238366] = { 238652 },
	[238371] = { 238652 },
	[238373] = { 238655 },
	[238374] = { 238654 },
	[238375] = { 238654 },
	[238380] = { 238656 },
	[238382] = { 238653 },
}
